version: "3.7"

services:

  app:
    build: ctf_challenge
    ports:
      - "127.0.0.1:8000:8000"

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Jaxn4*ZLCG_P*.@4wKrC
      ACCEPT_EULA: Y
